name: Labeler
on:
  push:
  pull_request:
    branches: 
      - master2
      
jobs:
  NewActions:
    runs-on: ubuntu-latest
    steps:
      - name: my job
        run: echo "My job, ${{ secrets.DOCKER_PASSWORD }}"
