name: Labeler
on:
  push:
  pull_request:
    branches: 
      - master2
      
jobs:
  NewActions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD_GITHUBACTIONS }}
      - name: Build and Push Docker Image
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: vasakkal/e-commerce-project:latest
        
